#!/usr/bin/env bash
# backup mysql database
name=$(date '+%d-%m-%Y')".tar.gz"
if [ -z "$1" ]
then
    echo 'Usage: ./1-mysql_backup <root password>'
    exit 1
fi
mysqldump -u root -p"$1"  --all-databases > "backup.sql"
tar -cvzf "$name" backup.sql